name: Hedera Integration Tests

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Create environment file
        run: |
          echo "HEDERA_NETWORK=testnet" >> .env
        
      - name: Run tests
        run: yarn test:dev
        # run: yarn test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            test-results
            cucumber-report.html
          retention-days: 7

  lint:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn lint

      - name: Run Prettier Check
        run: yarn format:check